/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import static java.lang.reflect.Array.set;
import javax.swing.table.DefaultTableModel;
import model.ActionHistory;
import model.adminset;
import model.appointment;
import model.appointmentlist;
import model.city;
import model.citylist;
import model.community;
import model.communityadminset;
import model.doctor;
import model.doctorset;
import model.encounterhistory;
import model.hospitaladminset;
import model.hospitallist;
import model.patientset;
import model.personset;

/**
 *
 * @author yueyingliang
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    communityadminset communityadminset;
    doctorset doctorset;
    adminset systemadminset;
    patientset patientset;
    appointmentlist appointmentlist;
    encounterhistory encounterhistory;
    hospitaladminset hospitaladminset;
    hospitallist hospitallist;
    personset personset;
    ActionHistory actionhistory;
    community community;
    city city;
    citylist citylist;
    
    public MainJFrame() {
        initComponents();
        systemadminset = new adminset();
        communityadminset = new communityadminset();
        hospitaladminset = new hospitaladminset();
        appointmentlist = new appointmentlist();
        encounterhistory = new encounterhistory();
        hospitallist = new hospitallist();
        actionhistory = new ActionHistory();
        
        doctorset = new doctorset();
        patientset = new patientset();
        personset = new personset();
        community = new community();
        city = new city();
        citylist = new citylist();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        ControlPlane = new javax.swing.JPanel();
        btnCommunityAdmin = new javax.swing.JButton();
        btnDoctor = new javax.swing.JButton();
        btnPatient = new javax.swing.JButton();
        btnSystemAdmin = new javax.swing.JButton();
        btnHospitalAdmin = new javax.swing.JButton();
        WorkArea = new javax.swing.JPanel();
        lblLoginPage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCommunityAdmin.setText("Community Admin");
        btnCommunityAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommunityAdminActionPerformed(evt);
            }
        });

        btnDoctor.setText("Doctor");
        btnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoctorActionPerformed(evt);
            }
        });

        btnPatient.setText("Patient ");
        btnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientActionPerformed(evt);
            }
        });

        btnSystemAdmin.setText("System Admin");
        btnSystemAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSystemAdminActionPerformed(evt);
            }
        });

        btnHospitalAdmin.setText("Hospital Admin");
        btnHospitalAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHospitalAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ControlPlaneLayout = new javax.swing.GroupLayout(ControlPlane);
        ControlPlane.setLayout(ControlPlaneLayout);
        ControlPlaneLayout.setHorizontalGroup(
            ControlPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPlaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ControlPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDoctor)
                    .addComponent(btnPatient)
                    .addComponent(btnSystemAdmin)
                    .addComponent(btnHospitalAdmin)
                    .addComponent(btnCommunityAdmin))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ControlPlaneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCommunityAdmin, btnDoctor, btnHospitalAdmin, btnPatient, btnSystemAdmin});

        ControlPlaneLayout.setVerticalGroup(
            ControlPlaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ControlPlaneLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(btnSystemAdmin)
                .addGap(32, 32, 32)
                .addComponent(btnHospitalAdmin)
                .addGap(36, 36, 36)
                .addComponent(btnCommunityAdmin)
                .addGap(36, 36, 36)
                .addComponent(btnDoctor)
                .addGap(36, 36, 36)
                .addComponent(btnPatient)
                .addContainerGap(270, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(ControlPlane);

        WorkArea.setPreferredSize(new java.awt.Dimension(800, 600));

        lblLoginPage.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblLoginPage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoginPage.setText("Log in Page");

        javax.swing.GroupLayout WorkAreaLayout = new javax.swing.GroupLayout(WorkArea);
        WorkArea.setLayout(WorkAreaLayout);
        WorkAreaLayout.setHorizontalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginPage, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE))
        );
        WorkAreaLayout.setVerticalGroup(
            WorkAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WorkAreaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginPage)
                .addContainerGap(577, Short.MAX_VALUE))
        );

        splitPane.setRightComponent(WorkArea);

        getContentPane().add(splitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoctorActionPerformed
        // TODO add your handling code here:
//        try to parse the appointmentlist object to the doctor panel.
        DoctorLoginPanel doctorloginPanel = new DoctorLoginPanel(systemadminset, 
                communityadminset, hospitaladminset, appointmentlist, doctorset, encounterhistory, hospitallist,
        patientset, personset, actionhistory, community, city, citylist);
        splitPane.setRightComponent(doctorloginPanel);
        doctorloginPanel.setVisible(true);
//        DoctorLoginPanel doctorloginPanel = new DoctorLoginPanel(appointmentlist, doctorset, encounterhistory);
//        splitPane.setRightComponent(doctorloginPanel);
//        doctorloginPanel.setVisible(true);
//        populateappointmentTable();
    }//GEN-LAST:event_btnDoctorActionPerformed

    private void btnCommunityAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommunityAdminActionPerformed
        // TODO add your handling code here:
        CommunityAdminLoginPanel adminloginPanel = new CommunityAdminLoginPanel(systemadminset, 
                communityadminset, hospitaladminset, appointmentlist, doctorset, encounterhistory, hospitallist,
        patientset, personset, actionhistory, community, city, citylist);
        splitPane.setRightComponent(adminloginPanel);
        adminloginPanel.setVisible(true);
//        CommunityAdminLoginPanel adminloginPanel = new CommunityAdminLoginPanel(communityadminset);
//        splitPane.setRightComponent(adminloginPanel);
//        adminloginPanel.setVisible(true);
    }//GEN-LAST:event_btnCommunityAdminActionPerformed

    private void btnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientActionPerformed
        // TODO add your handling code here:
        PatientLoginPanel patientloginPanel = new PatientLoginPanel(systemadminset, 
                communityadminset, hospitaladminset, appointmentlist, doctorset, encounterhistory, hospitallist,
        patientset, personset, actionhistory, community, city, citylist);
        splitPane.setRightComponent(patientloginPanel);
        patientloginPanel.setVisible(true);
//        PatientLoginPanel patientloginPanel = new PatientLoginPanel(appointmentlist, doctorset, encounterhistory);
//        splitPane.setRightComponent(patientloginPanel);
//        patientloginPanel.setVisible(true);
    }//GEN-LAST:event_btnPatientActionPerformed

    private void btnSystemAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSystemAdminActionPerformed
        // TODO add your handling code here:
        SystemAdminLoginPanel systemadminloginPanel = new SystemAdminLoginPanel(systemadminset, 
                communityadminset, hospitaladminset, appointmentlist, doctorset, encounterhistory, hospitallist,
        patientset, personset, actionhistory, community, city, citylist);
        splitPane.setRightComponent(systemadminloginPanel);
        systemadminloginPanel.setVisible(true);
    }//GEN-LAST:event_btnSystemAdminActionPerformed

    private void btnHospitalAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHospitalAdminActionPerformed
        // TODO add your handling code here:
        HospitalAdminLoginPanel hospitaladminloginPanel = new HospitalAdminLoginPanel(systemadminset, 
                communityadminset, hospitaladminset, appointmentlist, doctorset, encounterhistory, hospitallist,
        patientset, personset, actionhistory, community, city, citylist);
        splitPane.setRightComponent(hospitaladminloginPanel);
        hospitaladminloginPanel.setVisible(true);
//        HospitalAdminLoginPanel hospitaladminloginPanel = new HospitalAdminLoginPanel(hospitaladminset);
//        splitPane.setRightComponent(hospitaladminloginPanel);
//        hospitaladminloginPanel.setVisible(true);
    }//GEN-LAST:event_btnHospitalAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ControlPlane;
    private javax.swing.JPanel WorkArea;
    private javax.swing.JButton btnCommunityAdmin;
    private javax.swing.JButton btnDoctor;
    private javax.swing.JButton btnHospitalAdmin;
    private javax.swing.JButton btnPatient;
    private javax.swing.JButton btnSystemAdmin;
    private javax.swing.JLabel lblLoginPage;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

//    private void populateappointmentTable() {
//        DefaultTableModel model = (DefaultTableModel) DoctorLoginPanel.tblDoctorUpcomingEvents.getModel();
//        model.setRowCount(0);
//        doctor cd = doctorset.getHistory().get(index);
////        appointment ca = appointmentlist.getHistory().get(index);
//        
//        for (appointment ca : appointmentlist.getHistory()){
//            if (ca.getDoctorName().equals(cd.getName())) {
//                Object[] row = new Object[2];
//                row[0] = ca;
//                row[1] = ca.getPatientName();
//                model.addRow(row); 
//            }
//        }
//    }
}
