/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import static java.lang.reflect.Array.set;
import java.util.Date;
import static javax.management.Query.or;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.admin;
import model.adminset;
import model.patient;
import model.patientset;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.doctor;
import model.encounter;
import model.encounterhistory;

/**
 *
 * @author chengzhishi
 */
public class PatientLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminLoginPanel
     */
    patientset set;
    encounterhistory history;
    public int index;
    public PatientLoginPanel(patientset set) {
        initComponents();
        this.set = set;
        PatientProfileJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientEncounterHistoryJPanel.setVisible(false);
        ViewEncounterJPanel.setVisible(false);
        Date dl = new Date(2009,9,20);
        patient ei = set.addNewPatient();
        ei.setUsername("ABCDE");
        ei.setPassword("12345");
        ei.setPhoneNum("2143658709");
        ei.setEmailAdd("sjje9wi@slwk.com");
        ei.setGender("Male");
        ei.setName("ABCDE");
        ei.setDOB(dl);
        ei.setCity("AA");
        ei.setCommunity("AB");
        ei.setHomeAdd("pond str");
        ei.setPostalCode("01234");
        
        this.history = new encounterhistory();
        
        populateTable();
        
        encounter eh = history.addNewEncounter();
        Date ed = new Date(99, 3, 10);
        eh.setDoctorName("ABCD");
        eh.setPatientName("ABCDE");
        eh.setEncounterDate(ed);
        eh.setBloodPressure(100);
        eh.setHeartRate(90);
        eh.setTemperature(37);
        eh.setDiagnosis("Diabetes");
        eh.setNotes("Eat Less Sugar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        PatientLoginJPanel = new javax.swing.JPanel();
        lblPatientLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblNewUser = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        PatientProfileJPanel = new javax.swing.JPanel();
        lblCreatePassword = new javax.swing.JLabel();
        lblCreateUsername = new javax.swing.JLabel();
        txtShowUsername = new javax.swing.JTextField();
        txtShowPassword = new javax.swing.JPasswordField();
        lblName = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhoneNum = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        lblEmailAdd = new javax.swing.JLabel();
        txtEmailAdd = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblHomeAdd = new javax.swing.JLabel();
        txtHomeAdd = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        txtDOB = new javax.swing.JFormattedTextField();
        lblCity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblPostalCode = new javax.swing.JLabel();
        txtPostalCode = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        PatientWorkAreaJPanel = new javax.swing.JPanel();
        btnProfile = new javax.swing.JButton();
        btnEncounterHistory = new javax.swing.JButton();
        PatientCreateJPanel = new javax.swing.JPanel();
        lblCreateAccount4 = new javax.swing.JLabel();
        lblCreatePassword4 = new javax.swing.JLabel();
        lblCreateUsername4 = new javax.swing.JLabel();
        txtCreateUsername4 = new javax.swing.JTextField();
        txtCreatePassword4 = new javax.swing.JPasswordField();
        lblName4 = new javax.swing.JLabel();
        lblAdminInfo4 = new javax.swing.JLabel();
        lblDOB4 = new javax.swing.JLabel();
        txtName4 = new javax.swing.JTextField();
        lblPhoneNum4 = new javax.swing.JLabel();
        txtPhoneNum4 = new javax.swing.JTextField();
        lblEmailAdd4 = new javax.swing.JLabel();
        txtEmailAdd4 = new javax.swing.JTextField();
        lblGender4 = new javax.swing.JLabel();
        cmbGender4 = new javax.swing.JComboBox<>();
        lblHomeAdd4 = new javax.swing.JLabel();
        txtHomeAdd4 = new javax.swing.JTextField();
        btnCreate4 = new javax.swing.JButton();
        txtDOB4 = new javax.swing.JFormattedTextField();
        lblCity4 = new javax.swing.JLabel();
        txtCity4 = new javax.swing.JTextField();
        lblCommunity4 = new javax.swing.JLabel();
        txtCommunity4 = new javax.swing.JTextField();
        lblPostalCode4 = new javax.swing.JLabel();
        txtPostalCode4 = new javax.swing.JTextField();
        PatientEncounterHistoryJPanel = new javax.swing.JPanel();
        lblEncounterHistory = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEncounters = new javax.swing.JTable();
        cmbSearch = new javax.swing.JComboBox<>();
        btnSearch2 = new javax.swing.JButton();
        txtSearch2 = new javax.swing.JTextField();
        btnView = new javax.swing.JButton();
        btnBack1 = new javax.swing.JButton();
        ViewEncounterJPanel = new javax.swing.JPanel();
        lblEncounterDetail = new javax.swing.JLabel();
        lblPatientName = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        txtDoctorName = new javax.swing.JTextField();
        lblEncounterDate = new javax.swing.JLabel();
        lblDiagnosis = new javax.swing.JLabel();
        txtDiagnosis = new javax.swing.JTextField();
        lblBloodPressure = new javax.swing.JLabel();
        txtBloodPressure = new javax.swing.JTextField();
        lblHeartRate = new javax.swing.JLabel();
        txtHeartRate = new javax.swing.JTextField();
        txtEncounterDate = new javax.swing.JFormattedTextField();
        txtTemperature = new javax.swing.JTextField();
        lblTemperature = new javax.swing.JLabel();
        btnBack2 = new javax.swing.JButton();
        txtPatientName = new javax.swing.JTextField();
        lblNotes = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtNotes = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 255));
        setToolTipText("");
        setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        PatientLoginJPanel.setBackground(new java.awt.Color(255, 153, 0));

        lblPatientLogin.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblPatientLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPatientLogin.setText("Patient Login");

        lblUsername.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblPassword.setText("Password:");

        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblNewUser.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblNewUser.setText("New User?");

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientLoginJPanelLayout = new javax.swing.GroupLayout(PatientLoginJPanel);
        PatientLoginJPanel.setLayout(PatientLoginJPanelLayout);
        PatientLoginJPanelLayout.setHorizontalGroup(
            PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPatientLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PatientLoginJPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin)
                    .addGroup(PatientLoginJPanelLayout.createSequentialGroup()
                        .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword)
                            .addComponent(lblNewUser))
                        .addGap(18, 18, 18)
                        .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername)
                                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(335, Short.MAX_VALUE))
        );
        PatientLoginJPanelLayout.setVerticalGroup(
            PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientLoginJPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblPatientLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnLogin)
                .addGap(34, 34, 34)
                .addGroup(PatientLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUser)
                    .addComponent(btnCreateAccount))
                .addContainerGap(740, Short.MAX_VALUE))
        );

        jLayeredPane1.add(PatientLoginJPanel, "card2");

        PatientProfileJPanel.setBackground(new java.awt.Color(255, 153, 0));

        lblCreatePassword.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreatePassword.setText("Password:");

        lblCreateUsername.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreateUsername.setText("Username:");

        txtShowUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtShowUsernameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblName.setText("Name:");

        lblDOB.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblPhoneNum.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPhoneNum.setText("Phone Number:");

        lblEmailAdd.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblEmailAdd.setText("Email Address:");

        lblGender.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblGender.setText("Gender:");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "Non-Binary", "Prefer Not to Say", " " }));

        lblHomeAdd.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblHomeAdd.setText("Home Address:");

        txtHomeAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblCity.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCity.setText("City:");

        lblCommunity.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCommunity.setText("Community:");

        lblPostalCode.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPostalCode.setText("Postal Code:");

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientProfileJPanelLayout = new javax.swing.GroupLayout(PatientProfileJPanel);
        PatientProfileJPanel.setLayout(PatientProfileJPanelLayout);
        PatientProfileJPanelLayout.setHorizontalGroup(
            PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientProfileJPanelLayout.createSequentialGroup()
                            .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblGender))
                                    .addGap(18, 18, 18)
                                    .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(87, 87, 87)
                            .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDOB))))
                        .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                            .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEdit))
                                .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(87, 87, 87)
                                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCommunity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                            .addComponent(lblCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtShowUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(87, 87, 87)
                            .addComponent(lblCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        PatientProfileJPanelLayout.setVerticalGroup(
            PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientProfileJPanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtShowPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(PatientProfileJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate)
                    .addComponent(btnEdit))
                .addGap(52, 52, 52)
                .addComponent(btnBack)
                .addGap(38, 38, 38))
        );

        jLayeredPane1.add(PatientProfileJPanel, "card3");

        PatientWorkAreaJPanel.setBackground(new java.awt.Color(255, 153, 0));

        btnProfile.setText("Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnEncounterHistory.setText("Encounter History");
        btnEncounterHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncounterHistoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientWorkAreaJPanelLayout = new javax.swing.GroupLayout(PatientWorkAreaJPanel);
        PatientWorkAreaJPanel.setLayout(PatientWorkAreaJPanelLayout);
        PatientWorkAreaJPanelLayout.setHorizontalGroup(
            PatientWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PatientWorkAreaJPanelLayout.createSequentialGroup()
                .addContainerGap(438, Short.MAX_VALUE)
                .addComponent(btnEncounterHistory)
                .addGap(35, 35, 35)
                .addComponent(btnProfile)
                .addGap(132, 132, 132))
        );
        PatientWorkAreaJPanelLayout.setVerticalGroup(
            PatientWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientWorkAreaJPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(PatientWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProfile)
                    .addComponent(btnEncounterHistory))
                .addContainerGap(569, Short.MAX_VALUE))
        );

        jLayeredPane1.add(PatientWorkAreaJPanel, "card4");

        PatientCreateJPanel.setBackground(new java.awt.Color(255, 153, 0));

        lblCreateAccount4.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblCreateAccount4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount4.setText("Create a Patient Account");

        lblCreatePassword4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreatePassword4.setText("Password:");

        lblCreateUsername4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreateUsername4.setText("Username:");

        txtCreateUsername4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateUsername4ActionPerformed(evt);
            }
        });

        lblName4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblName4.setText("Name:");

        lblAdminInfo4.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblAdminInfo4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAdminInfo4.setText("New Patient Info");

        lblDOB4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblDOB4.setText("Date of Birth:");

        lblPhoneNum4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPhoneNum4.setText("Phone Number:");

        lblEmailAdd4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblEmailAdd4.setText("Email Address:");

        lblGender4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblGender4.setText("Gender:");

        cmbGender4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "Non-Binary", "Prefer Not to Say", " " }));

        lblHomeAdd4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblHomeAdd4.setText("Home Address:");

        txtHomeAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHomeAdd4ActionPerformed(evt);
            }
        });

        btnCreate4.setText("Create Account");
        btnCreate4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreate4ActionPerformed(evt);
            }
        });

        txtDOB4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDOB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOB4ActionPerformed(evt);
            }
        });

        lblCity4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCity4.setText("City:");

        lblCommunity4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCommunity4.setText("Community:");

        lblPostalCode4.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPostalCode4.setText("Postal Code:");

        javax.swing.GroupLayout PatientCreateJPanelLayout = new javax.swing.GroupLayout(PatientCreateJPanel);
        PatientCreateJPanel.setLayout(PatientCreateJPanelLayout);
        PatientCreateJPanelLayout.setHorizontalGroup(
            PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateAccount4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblAdminInfo4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                        .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                .addComponent(lblCreateUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCreateUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(lblCreatePassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCreatePassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                    .addComponent(lblPostalCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPostalCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                    .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                            .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGender4))
                                            .addGap(18, 18, 18)
                                            .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbGender4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(87, 87, 87)
                                    .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblEmailAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEmailAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblHomeAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtHomeAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDOB4))))))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                        .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCreate4)
                            .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                                .addComponent(lblCity4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCity4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(lblCommunity4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCommunity4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PatientCreateJPanelLayout.setVerticalGroup(
            PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientCreateJPanelLayout.createSequentialGroup()
                .addComponent(lblCreateAccount4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatePassword4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateUsername4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreatePassword4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblAdminInfo4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender4)
                    .addComponent(cmbGender4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHomeAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHomeAdd4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCity4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCommunity4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCommunity4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(PatientCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPostalCode4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPostalCode4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCreate4))
                .addGap(38, 38, 38))
        );

        jLayeredPane1.add(PatientCreateJPanel, "card5");

        PatientEncounterHistoryJPanel.setBackground(new java.awt.Color(255, 153, 0));
        PatientEncounterHistoryJPanel.setPreferredSize(new java.awt.Dimension(800, 600));

        lblEncounterHistory.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblEncounterHistory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncounterHistory.setText("Encounters");

        tblEncounters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Doctor", "Diagnosis"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblEncounters);

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Date", "Doctor", "Diagnosis" }));
        cmbSearch.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cmbSearchComponentAdded(evt);
            }
        });
        cmbSearch.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmbSearchComponentShown(evt);
            }
        });
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnBack1.setText("Back");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PatientEncounterHistoryJPanelLayout = new javax.swing.GroupLayout(PatientEncounterHistoryJPanel);
        PatientEncounterHistoryJPanel.setLayout(PatientEncounterHistoryJPanelLayout);
        PatientEncounterHistoryJPanelLayout.setHorizontalGroup(
            PatientEncounterHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientEncounterHistoryJPanelLayout.createSequentialGroup()
                .addComponent(lblEncounterHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 796, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 4, Short.MAX_VALUE))
            .addGroup(PatientEncounterHistoryJPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PatientEncounterHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PatientEncounterHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(btnView)
                        .addGap(37, 37, 37)
                        .addComponent(btnBack1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PatientEncounterHistoryJPanelLayout.createSequentialGroup()
                        .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnSearch2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearch2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PatientEncounterHistoryJPanelLayout.setVerticalGroup(
            PatientEncounterHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PatientEncounterHistoryJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEncounterHistory)
                .addGap(20, 20, 20)
                .addGroup(PatientEncounterHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch2)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PatientEncounterHistoryJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnBack1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        jLayeredPane1.add(PatientEncounterHistoryJPanel, "card6");

        ViewEncounterJPanel.setBackground(new java.awt.Color(255, 153, 0));

        lblEncounterDetail.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblEncounterDetail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEncounterDetail.setText("Encounter Detail");

        lblPatientName.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPatientName.setText("Patient:");

        lblDoctorName.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblDoctorName.setText("Doctor:");

        txtDoctorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorNameActionPerformed(evt);
            }
        });

        lblEncounterDate.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblEncounterDate.setText("Encounter Date:");

        lblDiagnosis.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblDiagnosis.setText("Diagnosis:");

        lblBloodPressure.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblBloodPressure.setText("Blood Pressure:");

        lblHeartRate.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblHeartRate.setText("Heart Rate:");

        txtEncounterDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtEncounterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEncounterDateActionPerformed(evt);
            }
        });

        lblTemperature.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblTemperature.setText("Temperature:");

        btnBack2.setText("Back");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        txtPatientName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientNameActionPerformed(evt);
            }
        });

        lblNotes.setText("Notes:");

        txtNotes.setColumns(20);
        txtNotes.setRows(5);
        jScrollPane3.setViewportView(txtNotes);

        javax.swing.GroupLayout ViewEncounterJPanelLayout = new javax.swing.GroupLayout(ViewEncounterJPanel);
        ViewEncounterJPanel.setLayout(ViewEncounterJPanelLayout);
        ViewEncounterJPanelLayout.setHorizontalGroup(
            ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblEncounterDetail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                        .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                .addComponent(lblDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewEncounterJPanelLayout.createSequentialGroup()
                                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                        .addComponent(lblBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(87, 87, 87))
                                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                        .addComponent(lblEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtEncounterDate)
                                        .addGap(86, 86, 86)))
                                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                        .addComponent(lblHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, Short.MAX_VALUE))
                                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                        .addComponent(lblDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                                .addComponent(lblNotes)
                                .addGap(78, 78, 78)
                                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewEncounterJPanelLayout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 238, Short.MAX_VALUE))
                                    .addComponent(btnBack2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap(154, Short.MAX_VALUE))
                    .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                        .addComponent(lblTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        ViewEncounterJPanelLayout.setVerticalGroup(
            ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewEncounterJPanelLayout.createSequentialGroup()
                .addComponent(lblEncounterDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDiagnosis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEncounterDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBloodPressure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeartRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTemperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(ViewEncounterJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotes)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(btnBack2)
                .addGap(72, 72, 72))
        );

        jLayeredPane1.add(ViewEncounterJPanel, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(true);
        
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
//        if (txtHomeAdd.getText().contains("[a-zA-Z]+")){
//            txtHomeAdd.setText("-1");
//        }
        
//        Date nonedate = new Date();

//        if (!txtDOB.getValue().equals(nonedate)){
//            Date DOB = (Date)txtDOB.getValue();
//
//        }
        String Username = txtShowUsername.getText();
        String Password = txtShowPassword.getText();
        String Name = txtName.getText();
        Date DOB = (Date)txtDOB.getValue();
//        int EmployeeID = Integer.parseInt(txtHomeAdd.getText());
        String Gender = cmbGender.getSelectedItem().toString();
        String PhoneNum = txtPhoneNum.getText();
        String EmailAdd = txtEmailAdd.getText();
        String HomeAdd = txtHomeAdd.getText();
        String City = txtCity.getText();
        String Community = txtCommunity.getText();
        String PostalCode = txtPostalCode.getText();
        
        int nameflag = 0;
        char[] charArray = Name.toCharArray();
        for(char c:charArray)
        {
        if (!Character.isLetter(c))
            nameflag = 1;
        }
        
        int phoneflag = 0;
        char[] PhoneArray = PhoneNum.toCharArray();
        for(char c:PhoneArray)
        {
        if (!Character.isDigit(c))
            phoneflag = 1;
        }
        
        int postalflag = 0;
        char[] PostalArray = PostalCode.toCharArray();
        for(char c:PostalArray)
        {
        if (!Character.isDigit(c))
            postalflag = 1;
        }
        
        int saveflag = 1;
        if (Username.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Username.");
            saveflag = 0;
        }
        if (Password.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Password.");   
            saveflag = 0;
        }
        if (Name.equals("") || nameflag == 1){
            JOptionPane.showMessageDialog(this, "Invalid Name.");
            saveflag = 0;
        }
        if (Gender.equals("None")){
            JOptionPane.showMessageDialog(this, "Invalid Gender.");
            saveflag = 0;
        }
        if (DOB == null){
            JOptionPane.showMessageDialog(this, "Invalid Date of Birth.");
            saveflag = 0;
        }
        if (PhoneNum.length() != 10 || phoneflag == 1){
            JOptionPane.showMessageDialog(this, "Invalid Phone Number.");
            saveflag = 0;
        }
        if (EmailAdd.equals("") || !EmailAdd.contains("@")){
            JOptionPane.showMessageDialog(this, "Invalid Email Address.");
            saveflag = 0;
        }
        if (HomeAdd.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Home Address.");   
            saveflag = 0;
        }
        if (City.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid City.");   
            saveflag = 0;
        }
        if (Community.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Community.");   
            saveflag = 0;
        }
        if (PostalCode.equals("") || postalflag == 1){
            JOptionPane.showMessageDialog(this, "Invalid Postal Code.");   
            saveflag = 0;
        }
        else if (saveflag == 1){
            
        patient ei = set.getHistory().get(index);
        ei.setUsername(Username);
        ei.setPassword(Password);
        ei.setPhoneNum(PhoneNum);
        ei.setEmailAdd(EmailAdd);
        ei.setGender(Gender);
        ei.setName(Name);
        ei.setDOB((Date)txtDOB.getValue());
        ei.setCity(City);
        ei.setCommunity(Community);
        ei.setPostalCode(PostalCode);
        ei.setHomeAdd(HomeAdd);
        JOptionPane.showMessageDialog(this, "Patient Information Updated.");
        
//        txtShowUsername.setText("");
//        txtShowPassword.setText("");
//        txtName.setText("");
//        txtDOB.setText("");
//        txtHomeAdd.setText("");
//        cmbGender.setSelectedIndex(0);
//        txtPhoneNum.setText("");
//        txtEmailAdd.setText("");
//        txtHomeAdd.setText("");
//        txtCity.setText("");
//        txtCommunity.setText("");
//        txtPostalCode.setText("");
        
//        PatientProfileJPanel.setVisible(false);
//        PatientLoginJPanel.setVisible(true);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = pwdPassword.getText();
        int flag = 0;
        int i = 0;
        for (patient ei : set.getHistory()){
            if (ei.getUsername().equals(username) & (ei.getPassword().equals(password))){
                flag = 1;
                index = i;
                PatientLoginJPanel.setVisible(false);
                PatientWorkAreaJPanel.setVisible(true);
                
            }
            else{
                i += 1;
            }
        }
        if(flag == 0){
            JOptionPane.showMessageDialog(this, "Wrong Username or Password.");
        }
//        admin ei = set.getHistory();
//        if (ei.getUsername().equals(username) & ei.getPassword().equals(password)){
//        
//    }
        
//        for(admin admin: this.set){
//            if (admin.getUsername().equals(username) and admin.getPassword().equals(password)){
//            
//        }
//        }
//        txtUsername.getText();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtShowUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtShowUsernameActionPerformed
        // TODO add your handling code here:
        
//        patient cp = new patient();
//        for (patient currentpatient : set.getHistory()){
//            if (currentpatient.getUsername().equals(txtUsername.getText()) & (currentpatient.getPassword().equals(pwdPassword.getText()))){
////                flag = 1;
//                patient cp = currentpatient;
//                txtShowUsername.setText(cp.getName());
//                txtShowUsername.setEditable(false);
//            }
//        }
        
    }//GEN-LAST:event_txtShowUsernameActionPerformed

    private void txtHomeAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeAddActionPerformed

    private void txtCreateUsername4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateUsername4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateUsername4ActionPerformed

    private void txtHomeAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHomeAdd4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHomeAdd4ActionPerformed

    private void btnCreate4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreate4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreate4ActionPerformed

    private void txtDOB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOB4ActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(true);
        patient cp = set.getHistory().get(index);
        
        txtShowUsername.setText(cp.getName());
        txtShowUsername.setEditable(false);
        
        txtShowPassword.setText(cp.getPassword());
        txtShowPassword.setEditable(false);
        
        txtName.setText(cp.getName());
        txtName.setEditable(false);
        
        txtDOB.setValue(cp.getDOB());
        txtDOB.setEditable(false);
        
        txtPhoneNum.setText(cp.getPhoneNum());
        txtPhoneNum.setEditable(false);
        
        txtEmailAdd.setText(cp.getEmailAdd());
        txtEmailAdd.setEditable(false);
        
        cmbGender.setSelectedItem(cp.getGender());
        cmbGender.setEnabled(false);
        
        txtHomeAdd.setText(cp.getHomeAdd());
        txtHomeAdd.setEditable(false);
        
        txtCity.setText(cp.getCity());
        txtCity.setEditable(false);
        
        txtCommunity.setText(cp.getCommunity());
        txtCommunity.setEditable(false);
        
        txtPostalCode.setText(cp.getPostalCode());
        txtPostalCode.setEditable(false);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        txtShowUsername.setEditable(true);
        txtShowPassword.setEditable(true);
        txtName.setEditable(true);
        txtDOB.setEditable(true);
        txtPhoneNum.setEditable(true);
        txtEmailAdd.setEditable(true);
        cmbGender.setEnabled(true);
        txtHomeAdd.setEditable(true);
        txtCity.setEditable(true);
        txtCommunity.setEditable(true);
        txtPostalCode.setEditable(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbSearchComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cmbSearchComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchComponentAdded

    private void cmbSearchComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbSearchComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchComponentShown

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
        //        System.out.println(cmbSearch.getSelectedItem().toString());
        if (cmbSearch.getSelectedItem().toString().matches("All")) {
            DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            tblEncounters.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim()));
        }
        //
        else if (cmbSearch.getSelectedItem().toString().matches("Date")) {

            DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            tblEncounters.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 0));
        }
        //
        else if (cmbSearch.getSelectedItem().toString().matches("Doctor")) {

            DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            tblEncounters.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 1));
        }

        else if (cmbSearch.getSelectedItem().toString().matches("Diagnosis")) {

            DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            tblEncounters.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 2));
        }

        //
        //        else if (cmbSearch.getSelectedItem().toString().matches("Level")) {
            //
            //            DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
            //            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            //            tblOverview.setRowSorter(tr);
            //            tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 3));
            //        }
        ////            Vector rowVector = (Vector) rows;
        //            for (int j = 0; j < tblOverview.getColumnCount(); j++){
            //            }
        //            }
        //        }
        //
        //        if(cmbSearch.getSelectedItem().toString() != "All" && txtSearch2.getText().isBlank()){
            //            JOptionPane.showMessageDialog(null, "Please enter a keyword or select All items");
            //        }else{
            //            for(int i = 0; i < tblOverview.getRowCount(); i++){//For each row
                //                for(int j = 0; j < tblOverview.getColumnCount(); j++){//For each column in that row
                    //                    if(tblOverview.getModel().getValueAt(i, j).equals(txtSearch2.getText())){//Search the model
                        //                        System.out.println(tblOverview.getModel().getValueAt(i, j));//Print if found string
                        //                    }
                    //                }//For loop inner
                //}//For loop outer
            ////            List<EmployeeInfo> filteredList = history.Search(cmbSearch.getSelectedItem().toString(), txtSearch2.getText());
            ////            displayTable(filteredList);
            //        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblEncounters.getSelectedRow();
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select a Row to View.");
            return;
        }
        PatientLoginJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(false);
        PatientEncounterHistoryJPanel.setVisible(false);
        ViewEncounterJPanel.setVisible(true);
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        encounter selectedEncounter = (encounter) model.getValueAt(selectedRowIndex, 0);

        txtDoctorName.setText(selectedEncounter.getDoctorName());
        txtDoctorName.setEditable(false);

        txtPatientName.setText(selectedEncounter.getPatientName());
        txtPatientName.setEditable(false);

        txtEncounterDate.setValue(selectedEncounter.getEncounterDate());
        txtEncounterDate.setEditable(false);

        txtDiagnosis.setText(selectedEncounter.getDiagnosis());
        txtDiagnosis.setEditable(false);

        txtBloodPressure.setText(String.valueOf(selectedEncounter.getBloodPressure()));
        txtBloodPressure.setEditable(false);

        txtHeartRate.setText(String.valueOf(selectedEncounter.getHeartRate()));
        txtHeartRate.setEditable(false);

        txtTemperature.setText(String.valueOf(selectedEncounter.getTemperature()));
        txtTemperature.setEditable(false);

        txtNotes.setText(selectedEncounter.getNotes());
        txtNotes.setEditable(false);
        //        txtAge.setText(String.valueOf(selectedEmployee.getAge()));
        //        txtCellNum.setText(selectedEmployee.getCellNum());
        //        cmbGender.setSelectedItem(selectedEmployee.getGender());
        //        txtEmailAdd.setText(selectedEmployee.getEmailAdd());
        //        txtEmployeeID.setText(String.valueOf(selectedEmployee.getEmployeeID()));
        //        txtStartDate.setValue(selectedEmployee.getStartDate());
        //        txtLevel.setText(String.valueOf(selectedEmployee.getLevel()));
        //        txtTeamInfo.setText(selectedEmployee.getTeaminfo());
        //        txtPosTitle.setText(selectedEmployee.getPositionTitle());
        //        lblPicture.setIcon(selectedEmployee.getImage());
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        // TODO add your handling code here:
        PatientProfileJPanel.setVisible(false);
        PatientLoginJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        ViewEncounterJPanel.setVisible(false);
        PatientEncounterHistoryJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(true);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void txtDoctorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorNameActionPerformed

    private void txtEncounterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEncounterDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEncounterDateActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        ViewEncounterJPanel.setVisible(false);
        PatientEncounterHistoryJPanel.setVisible(true);
    }//GEN-LAST:event_btnBack2ActionPerformed

    private void txtPatientNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientNameActionPerformed

    private void btnEncounterHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncounterHistoryActionPerformed
        // TODO add your handling code here:
        PatientLoginJPanel.setVisible(false);
        ViewEncounterJPanel.setVisible(false);
        PatientCreateJPanel.setVisible(false);
        PatientWorkAreaJPanel.setVisible(false);
        PatientProfileJPanel.setVisible(false);
        PatientEncounterHistoryJPanel.setVisible(true);
        
        populateTable();
    }//GEN-LAST:event_btnEncounterHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientCreateJPanel;
    private javax.swing.JPanel PatientCreateJPanel1;
    private javax.swing.JPanel PatientCreateJPanel2;
    private javax.swing.JPanel PatientCreateJPanel3;
    private javax.swing.JPanel PatientEncounterHistoryJPanel;
    private javax.swing.JPanel PatientLoginJPanel;
    private javax.swing.JPanel PatientProfileJPanel;
    private javax.swing.JPanel PatientWorkAreaJPanel;
    private javax.swing.JPanel ViewEncounterJPanel;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnCreate1;
    private javax.swing.JButton btnCreate2;
    private javax.swing.JButton btnCreate3;
    private javax.swing.JButton btnCreate4;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEncounterHistory;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbGender1;
    private javax.swing.JComboBox<String> cmbGender2;
    private javax.swing.JComboBox<String> cmbGender3;
    private javax.swing.JComboBox<String> cmbGender4;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAdminInfo1;
    private javax.swing.JLabel lblAdminInfo2;
    private javax.swing.JLabel lblAdminInfo3;
    private javax.swing.JLabel lblAdminInfo4;
    private javax.swing.JLabel lblBloodPressure;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCity1;
    private javax.swing.JLabel lblCity2;
    private javax.swing.JLabel lblCity3;
    private javax.swing.JLabel lblCity4;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblCommunity1;
    private javax.swing.JLabel lblCommunity2;
    private javax.swing.JLabel lblCommunity3;
    private javax.swing.JLabel lblCommunity4;
    private javax.swing.JLabel lblCreateAccount1;
    private javax.swing.JLabel lblCreateAccount2;
    private javax.swing.JLabel lblCreateAccount3;
    private javax.swing.JLabel lblCreateAccount4;
    private javax.swing.JLabel lblCreatePassword;
    private javax.swing.JLabel lblCreatePassword1;
    private javax.swing.JLabel lblCreatePassword2;
    private javax.swing.JLabel lblCreatePassword3;
    private javax.swing.JLabel lblCreatePassword4;
    private javax.swing.JLabel lblCreateUsername;
    private javax.swing.JLabel lblCreateUsername1;
    private javax.swing.JLabel lblCreateUsername2;
    private javax.swing.JLabel lblCreateUsername3;
    private javax.swing.JLabel lblCreateUsername4;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblDOB2;
    private javax.swing.JLabel lblDOB3;
    private javax.swing.JLabel lblDOB4;
    private javax.swing.JLabel lblDiagnosis;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblEmailAdd1;
    private javax.swing.JLabel lblEmailAdd2;
    private javax.swing.JLabel lblEmailAdd3;
    private javax.swing.JLabel lblEmailAdd4;
    private javax.swing.JLabel lblEncounterDate;
    private javax.swing.JLabel lblEncounterDetail;
    private javax.swing.JLabel lblEncounterHistory;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblGender2;
    private javax.swing.JLabel lblGender3;
    private javax.swing.JLabel lblGender4;
    private javax.swing.JLabel lblHeartRate;
    private javax.swing.JLabel lblHomeAdd;
    private javax.swing.JLabel lblHomeAdd1;
    private javax.swing.JLabel lblHomeAdd2;
    private javax.swing.JLabel lblHomeAdd3;
    private javax.swing.JLabel lblHomeAdd4;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblNotes;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPatientLogin;
    private javax.swing.JLabel lblPatientName;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblPhoneNum1;
    private javax.swing.JLabel lblPhoneNum2;
    private javax.swing.JLabel lblPhoneNum3;
    private javax.swing.JLabel lblPhoneNum4;
    private javax.swing.JLabel lblPostalCode;
    private javax.swing.JLabel lblPostalCode1;
    private javax.swing.JLabel lblPostalCode2;
    private javax.swing.JLabel lblPostalCode3;
    private javax.swing.JLabel lblPostalCode4;
    private javax.swing.JLabel lblTemperature;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JTable tblEncounters;
    private javax.swing.JTextField txtBloodPressure;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCity1;
    private javax.swing.JTextField txtCity2;
    private javax.swing.JTextField txtCity3;
    private javax.swing.JTextField txtCity4;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtCommunity1;
    private javax.swing.JTextField txtCommunity2;
    private javax.swing.JTextField txtCommunity3;
    private javax.swing.JTextField txtCommunity4;
    private javax.swing.JPasswordField txtCreatePassword1;
    private javax.swing.JPasswordField txtCreatePassword2;
    private javax.swing.JPasswordField txtCreatePassword3;
    private javax.swing.JPasswordField txtCreatePassword4;
    private javax.swing.JTextField txtCreateUsername1;
    private javax.swing.JTextField txtCreateUsername2;
    private javax.swing.JTextField txtCreateUsername3;
    private javax.swing.JTextField txtCreateUsername4;
    private javax.swing.JFormattedTextField txtDOB;
    private javax.swing.JFormattedTextField txtDOB1;
    private javax.swing.JFormattedTextField txtDOB2;
    private javax.swing.JFormattedTextField txtDOB3;
    private javax.swing.JFormattedTextField txtDOB4;
    private javax.swing.JTextField txtDiagnosis;
    private javax.swing.JTextField txtDoctorName;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtEmailAdd1;
    private javax.swing.JTextField txtEmailAdd2;
    private javax.swing.JTextField txtEmailAdd3;
    private javax.swing.JTextField txtEmailAdd4;
    private javax.swing.JFormattedTextField txtEncounterDate;
    private javax.swing.JTextField txtHeartRate;
    private javax.swing.JTextField txtHomeAdd;
    private javax.swing.JTextField txtHomeAdd1;
    private javax.swing.JTextField txtHomeAdd2;
    private javax.swing.JTextField txtHomeAdd3;
    private javax.swing.JTextField txtHomeAdd4;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtName2;
    private javax.swing.JTextField txtName3;
    private javax.swing.JTextField txtName4;
    private javax.swing.JTextArea txtNotes;
    private javax.swing.JTextField txtPatientName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtPhoneNum1;
    private javax.swing.JTextField txtPhoneNum2;
    private javax.swing.JTextField txtPhoneNum3;
    private javax.swing.JTextField txtPhoneNum4;
    private javax.swing.JTextField txtPostalCode;
    private javax.swing.JTextField txtPostalCode1;
    private javax.swing.JTextField txtPostalCode2;
    private javax.swing.JTextField txtPostalCode3;
    private javax.swing.JTextField txtPostalCode4;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JPasswordField txtShowPassword;
    private javax.swing.JTextField txtShowUsername;
    private javax.swing.JTextField txtTemperature;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblEncounters.getModel();
        model.setRowCount(0);
        patient cp = set.getHistory().get(index);
        
        for (encounter eh : history.getHistory()){
            if (eh.getPatientName().equals(cp.getName())) {
                Object[] row = new Object[3];
                row[0] = eh;
                row[1] = eh.getPatientName();
                row[2] = eh.getDiagnosis();

                model.addRow(row); 
            }
        }
        
    }
}
