/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.EmployeeInfo;
import model.EmployeeInfoHistory;

/**
 *
 * @author yueyingliang
 */

public class OverviewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form OverviewJPanel
     */
    
    EmployeeInfoHistory history;
    public OverviewJPanel(EmployeeInfoHistory history) {
        initComponents();
        this.history = history;
        ViewDetailJPanel.setVisible(false);
        
        populateTable();
    }
    public void displayTable(List<EmployeeInfo> emp){
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        model.setRowCount(0);
        for(EmployeeInfo employee : history.getHistory()){
            Object[] row = new Object[11];
            row[0] = employee.getName();
            row[1] = employee.getEmployeeID();
            row[2] = employee.getAge();
            row[3] = employee.getGender();
            row[4] = employee.getStartDate();
            row[5] = employee.getLevel();
            row[6] = employee.getTeaminfo();
            row[7] = employee.getPositionTitle();
            row[8] = employee.getCellNum();
            row[9] = employee.getEmailAdd();
//            row[10] = employee.getPhoto();
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        OverviewJPanel = new javax.swing.JPanel();
        lblOverview2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOverview = new javax.swing.JTable();
        btnView2 = new javax.swing.JButton();
        btnDelete2 = new javax.swing.JButton();
        btnSearch2 = new javax.swing.JButton();
        txtSearch2 = new javax.swing.JTextField();
        cmbSearch = new javax.swing.JComboBox<>();
        ViewDetailJPanel = new javax.swing.JPanel();
        txtLevel = new javax.swing.JTextField();
        lblCellNum = new javax.swing.JLabel();
        txtCellNum = new javax.swing.JTextField();
        lblEmailAdd = new javax.swing.JLabel();
        txtEmailAdd = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblPersonalInfo = new javax.swing.JLabel();
        lblEmployInfo = new javax.swing.JLabel();
        lblEmployeeID = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblContactInfo = new javax.swing.JLabel();
        lblPosTitle = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPosTitle = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        txtStartDate = new javax.swing.JFormattedTextField();
        lblPicture = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();

        lblOverview2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblOverview2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOverview2.setText("Overview");

        tblOverview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Team Info", "Position Title", "Level"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblOverview);

        btnView2.setText("View");
        btnView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnView2ActionPerformed(evt);
            }
        });

        btnDelete2.setText("Delete");
        btnDelete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete2ActionPerformed(evt);
            }
        });

        btnSearch2.setText("Search");
        btnSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch2ActionPerformed(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Name", "Level", "Position Title", "Team Info" }));
        cmbSearch.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                cmbSearchComponentAdded(evt);
            }
        });
        cmbSearch.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                cmbSearchComponentShown(evt);
            }
        });
        cmbSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OverviewJPanelLayout = new javax.swing.GroupLayout(OverviewJPanel);
        OverviewJPanel.setLayout(OverviewJPanelLayout);
        OverviewJPanelLayout.setHorizontalGroup(
            OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverviewJPanelLayout.createSequentialGroup()
                .addGroup(OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOverview2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                    .addGroup(OverviewJPanelLayout.createSequentialGroup()
                        .addContainerGap(444, Short.MAX_VALUE)
                        .addComponent(btnView2)
                        .addGap(191, 191, 191)))
                .addGap(69, 69, 69))
            .addGroup(OverviewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDelete2)
                    .addGroup(OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(OverviewJPanelLayout.createSequentialGroup()
                            .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(12, 12, 12)
                            .addComponent(btnSearch2)
                            .addGap(18, 18, 18)
                            .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        OverviewJPanelLayout.setVerticalGroup(
            OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OverviewJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblOverview2)
                .addGap(31, 31, 31)
                .addGroup(OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch2)
                    .addComponent(txtSearch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(OverviewJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView2)
                    .addComponent(btnDelete2))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        txtLevel.setEditable(false);

        lblCellNum.setText("Cell Phone Number:");

        txtCellNum.setEditable(false);
        txtCellNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCellNumActionPerformed(evt);
            }
        });

        lblEmailAdd.setText("Email Address:");

        txtEmailAdd.setEditable(false);
        txtEmailAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailAddActionPerformed(evt);
            }
        });

        lblPersonalInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblPersonalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonalInfo.setText("Personal Info");

        lblEmployInfo.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblEmployInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmployInfo.setText("Employment Info");

        lblEmployeeID.setText("Employee ID:");

        lblName.setText("Name:");

        lblStartDate.setText("Start Date:");

        lblAge.setText("Age:");

        lblLevel.setText("Level:");

        lblGender.setText("Gender:");

        lblTeamInfo.setText("Team Info:");

        lblContactInfo.setText("Contact Info:");

        lblPosTitle.setText("Position Title:");

        txtEmployeeID.setEditable(false);

        txtName.setEditable(false);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        txtAge.setEditable(false);

        txtTeamInfo.setEditable(false);

        txtPosTitle.setEditable(false);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnUpload.setText("Upload");
        btnUpload.setEnabled(false);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        txtStartDate.setEditable(false);
        txtStartDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        lblPicture.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPicture.setText("Photo Here");
        lblPicture.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Non-Binary", "Prefer Not to Say", " " }));
        cmbGender.setEnabled(false);

        javax.swing.GroupLayout ViewDetailJPanelLayout = new javax.swing.GroupLayout(ViewDetailJPanel);
        ViewDetailJPanel.setLayout(ViewDetailJPanelLayout);
        ViewDetailJPanelLayout.setHorizontalGroup(
            ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDetailJPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDetailJPanelLayout.createSequentialGroup()
                        .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ViewDetailJPanelLayout.createSequentialGroup()
                        .addComponent(btnUpload)
                        .addGap(100, 100, 100))))
            .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(65, 65, 65))
                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addComponent(lblPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblGender)
                                    .addComponent(lblName)
                                    .addComponent(lblAge))
                                .addGap(18, 18, 18)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtName)
                                    .addComponent(txtAge)
                                    .addComponent(cmbGender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(70, 70, 70)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCellNum)
                                    .addComponent(lblContactInfo)
                                    .addComponent(lblEmailAdd))
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCellNum)
                                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                        .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblLevel)
                                .addComponent(lblEmployInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmployeeID)
                                    .addComponent(lblTeamInfo))
                                .addGap(18, 18, 18)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                                        .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(lblPosTitle))
                                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                                        .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblStartDate)))
                                .addGap(18, 18, 18)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ViewDetailJPanelLayout.setVerticalGroup(
            ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                        .addComponent(lblPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ViewDetailJPanelLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCellNum)
                                    .addComponent(txtCellNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblGender)
                                    .addComponent(lblEmailAdd)
                                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblContactInfo))))
                    .addComponent(lblPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpload)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblEmployInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmployeeID)
                    .addComponent(lblStartDate)
                    .addComponent(lblLevel)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTeamInfo)
                    .addComponent(lblPosTitle)
                    .addComponent(txtTeamInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(ViewDetailJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnEdit))
                .addGap(70, 70, 70))
        );

        jLayeredPane2.setLayer(OverviewJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(ViewDetailJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(ViewDetailJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 70, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(0, 15, Short.MAX_VALUE)
                    .addComponent(OverviewJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 16, Short.MAX_VALUE)))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(ViewDetailJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 606, Short.MAX_VALUE))
            .addGroup(jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(OverviewJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 600, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCellNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCellNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCellNumActionPerformed

    private void txtEmailAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailAddActionPerformed
//    private void filter(String query){
//        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>((DefaultTableModel)tblOverview.getModel());
//        tblOverview.setRowSorter(tr);
//        
//        tr.setRowFilter(RowFilter.regexFilter(query));
//        
//    }
    
    private void btnSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch2ActionPerformed
        // TODO add your handling code here:
//        System.out.println(cmbSearch.getSelectedItem().toString());
        if (cmbSearch.getSelectedItem().toString().matches("All")) {
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblOverview.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim()));
        }
        
        else if (cmbSearch.getSelectedItem().toString().matches("Name")) {
 
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblOverview.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 0));
        }
        
        else if (cmbSearch.getSelectedItem().toString().matches("Team Info")) {
 
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblOverview.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 1));
        }
        
        else if (cmbSearch.getSelectedItem().toString().matches("Position Title")) {
 
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblOverview.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 2));
        }
        
        else if (cmbSearch.getSelectedItem().toString().matches("Level")) {
 
        DefaultTableModel model = (DefaultTableModel) tblOverview.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        tblOverview.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txtSearch2.getText().trim(), 3));
        }
////            Vector rowVector = (Vector) rows;
//            for (int j = 0; j < tblOverview.getColumnCount(); j++){
//            }
//            }
//        }
//        
//        if(cmbSearch.getSelectedItem().toString() != "All" && txtSearch2.getText().isBlank()){
//            JOptionPane.showMessageDialog(null, "Please enter a keyword or select All items");
//        }else{
//            for(int i = 0; i < tblOverview.getRowCount(); i++){//For each row
//                for(int j = 0; j < tblOverview.getColumnCount(); j++){//For each column in that row
//                    if(tblOverview.getModel().getValueAt(i, j).equals(txtSearch2.getText())){//Search the model
//                        System.out.println(tblOverview.getModel().getValueAt(i, j));//Print if found string
//                    }
//                }//For loop inner
//}//For loop outer
////            List<EmployeeInfo> filteredList = history.Search(cmbSearch.getSelectedItem().toString(), txtSearch2.getText());
////            displayTable(filteredList);
//        }
    }//GEN-LAST:event_btnSearch2ActionPerformed

    private void btnView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnView2ActionPerformed
        // TODO add your handling code here:
        ViewDetailJPanel.setVisible(true);
        OverviewJPanel.setVisible(false);
        
        int selectedRowIndex = tblOverview.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select A Row To View.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tblOverview.getModel();
        EmployeeInfo selectedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        txtName.setText(selectedEmployee.getName());
        txtAge.setText(String.valueOf(selectedEmployee.getAge()));
        txtCellNum.setText(selectedEmployee.getCellNum());
        cmbGender.setSelectedItem(selectedEmployee.getGender());
        txtEmailAdd.setText(selectedEmployee.getEmailAdd());
        txtEmployeeID.setText(String.valueOf(selectedEmployee.getEmployeeID()));
        txtStartDate.setValue(selectedEmployee.getStartDate());
        txtLevel.setText(String.valueOf(selectedEmployee.getLevel()));
        txtTeamInfo.setText(selectedEmployee.getTeaminfo());
        txtPosTitle.setText(selectedEmployee.getPositionTitle());
        lblPicture.setIcon(selectedEmployee.getImage());
        
    }//GEN-LAST:event_btnView2ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblOverview.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select A Row To Delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tblOverview.getModel();
        EmployeeInfo selectedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        history.deleteEmployee(selectedEmployee);
        
        String Name = txtName.getText();
        int Age = Integer.parseInt(txtAge.getText());
        int EmployeeID = Integer.parseInt(txtEmployeeID.getText());
        String Gender = cmbGender.getSelectedItem().toString();
        Date StartDate = (Date)txtStartDate.getValue();
        int Level = Integer.parseInt(txtLevel.getText());
        String Teaminfo = txtTeamInfo.getText();
        String PositionTitle = txtPosTitle.getText();
        String CellNum = txtCellNum.getText();
        String EmailAdd = txtEmailAdd.getText();
        ImageIcon image = (ImageIcon)lblPicture.getIcon();
        
        EmployeeInfo ei = history.addNewEmployees();
        ei.setAge(Age);
        ei.setCellNum(CellNum);
        ei.setEmailAdd(EmailAdd);
        ei.setEmployeeID(EmployeeID);
        ei.setGender(Gender);
        ei.setLevel(Level);
        ei.setName(Name);
        ei.setStartDate(StartDate);
        ei.setTeaminfo(Teaminfo);
        ei.setPositionTitle(PositionTitle);
        ei.setImage(image);
        
        JOptionPane.showMessageDialog(this, "Employee Info Updated.");
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDelete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblOverview.getSelectedRow();
        
        if (selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please Select A Row To Delete.");
            return;
        }
        DefaultTableModel model = (DefaultTableModel)tblOverview.getModel();
        EmployeeInfo selectedEmployee = (EmployeeInfo)model.getValueAt(selectedRowIndex, 0);
        
        history.deleteEmployee(selectedEmployee);
        
        JOptionPane.showMessageDialog(this, "Successfully Deleted.");
        
        populateTable();
    }//GEN-LAST:event_btnDelete2ActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        
        txtName.setEditable(true);
        txtAge.setEditable(true);
        txtCellNum.setEditable(true);
        cmbGender.setEnabled(true);
        txtEmailAdd.setEditable(true);
        txtEmployeeID.setEditable(true);
        txtStartDate.setEditable(true);
        txtLevel.setEditable(true);
        txtTeamInfo.setEditable(true);
        txtPosTitle.setEditable(true);
        btnUpload.setEnabled(true);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser filechooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("4 Extensions Supported", "jpg", "png", "jpeg", "gif");
        filechooser.setFileFilter(filter);
        int selected = filechooser.showOpenDialog(null);
        if (selected == JFileChooser.APPROVE_OPTION){
            File file = filechooser.getSelectedFile();
            
            String getselectedImage = file.getAbsolutePath();
            JOptionPane.showMessageDialog(null, "Image Uploaded.");
            
            ImageIcon imIco = new ImageIcon(getselectedImage);
            Image imFit = imIco.getImage();
            Image imgFit = imFit.getScaledInstance(lblPicture.getWidth(), lblPicture.getHeight(), Image.SCALE_SMOOTH);
            lblPicture.setIcon(new ImageIcon(imgFit));
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void cmbSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchActionPerformed

    private void cmbSearchComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_cmbSearchComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchComponentShown

    private void cmbSearchComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_cmbSearchComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchComponentAdded


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OverviewJPanel;
    private javax.swing.JPanel ViewDetailJPanel;
    private javax.swing.JButton btnDelete2;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSearch2;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton btnView2;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCellNum;
    private javax.swing.JLabel lblContactInfo;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblEmployInfo;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOverview2;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblPicture;
    private javax.swing.JLabel lblPosTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JTable tblOverview;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCellNum;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPosTitle;
    private javax.swing.JTextField txtSearch2;
    private javax.swing.JFormattedTextField txtStartDate;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel)tblOverview.getModel();
        model.setRowCount(0);
        
        for (EmployeeInfo ei : history.getHistory()){
            
            Object[] row = new Object[4];
            row[0] = ei;
            row[1] = ei.getTeaminfo();
            row[2] = ei.getPositionTitle();
            row[3] = ei.getLevel();
            
            model.addRow(row);
        }
    }
}
