/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import static java.lang.reflect.Array.set;
import java.util.Date;
import static javax.management.Query.or;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.admin;
import model.adminset;
import model.doctor;
import model.doctorset;

/**
 *
 * @author chengzhishi
 */
public class DoctorLoginPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorLoginPanel
     */
    doctorset set;
    public DoctorLoginPanel(doctorset set) {
        initComponents();
        this.set = set;
        DoctorCreateJPanel.setVisible(false);
        Date dl = new Date(10,10,2002);
        doctor ei = set.addNewDoctor();
        ei.setUsername("ABCD");
        ei.setPassword("1234");
        ei.setPhoneNum("9876543210");
        ei.setEmailAdd("swiau@sme.com");
        ei.setEmployeeID(2);
        ei.setGender("Male");
        ei.setName("ABCD");
        ei.setDOB(dl);
        ei.setHospital("AAA");
        ei.setMajor("BBB");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        DoctorLoginJPanel = new javax.swing.JPanel();
        lblDoctorLogin = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        pwdPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        lblNewUser = new javax.swing.JLabel();
        btnCreateAccount = new javax.swing.JButton();
        DoctorCreateJPanel = new javax.swing.JPanel();
        lblCreateAccount = new javax.swing.JLabel();
        lblCreatePassword = new javax.swing.JLabel();
        lblCreateUsername = new javax.swing.JLabel();
        txtCreateUsername = new javax.swing.JTextField();
        txtCreatePassword = new javax.swing.JPasswordField();
        lblName = new javax.swing.JLabel();
        lblDoctorInfo = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblPhoneNum = new javax.swing.JLabel();
        txtPhoneNum = new javax.swing.JTextField();
        lblEmailAdd = new javax.swing.JLabel();
        txtEmailAdd = new javax.swing.JTextField();
        lblGender = new javax.swing.JLabel();
        cmbGender = new javax.swing.JComboBox<>();
        lblEmployeeID = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        btnCreate = new javax.swing.JButton();
        txtDOB = new javax.swing.JFormattedTextField();
        txtHospital = new javax.swing.JTextField();
        lblHospital = new javax.swing.JLabel();
        lblMajor = new javax.swing.JLabel();
        txtMajor = new javax.swing.JTextField();
        DoctorWorkAreaJPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 255));
        setToolTipText("");
        setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N

        DoctorLoginJPanel.setBackground(new java.awt.Color(51, 255, 51));

        lblDoctorLogin.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblDoctorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorLogin.setText("Doctor Login");

        lblUsername.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblUsername.setText("Username:");

        lblPassword.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblPassword.setText("Password:");

        pwdPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPasswordActionPerformed(evt);
            }
        });

        btnLogin.setText("Log in");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblNewUser.setFont(new java.awt.Font("Klee", 1, 18)); // NOI18N
        lblNewUser.setText("New User?");

        btnCreateAccount.setText("Create Account");
        btnCreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateAccountActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorLoginJPanelLayout = new javax.swing.GroupLayout(DoctorLoginJPanel);
        DoctorLoginJPanel.setLayout(DoctorLoginJPanelLayout);
        DoctorLoginJPanelLayout.setHorizontalGroup(
            DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblDoctorLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DoctorLoginJPanelLayout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLogin)
                    .addGroup(DoctorLoginJPanelLayout.createSequentialGroup()
                        .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(lblPassword)
                            .addComponent(lblNewUser))
                        .addGap(18, 18, 18)
                        .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtUsername)
                                .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreateAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        DoctorLoginJPanelLayout.setVerticalGroup(
            DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorLoginJPanelLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lblDoctorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pwdPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnLogin)
                .addGap(34, 34, 34)
                .addGroup(DoctorLoginJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNewUser)
                    .addComponent(btnCreateAccount))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        DoctorCreateJPanel.setBackground(new java.awt.Color(51, 255, 51));

        lblCreateAccount.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblCreateAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCreateAccount.setText("Create a Doctor Account");

        lblCreatePassword.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreatePassword.setText("Password:");

        lblCreateUsername.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblCreateUsername.setText("Username:");

        txtCreateUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateUsernameActionPerformed(evt);
            }
        });

        lblName.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblName.setText("Name:");

        lblDoctorInfo.setFont(new java.awt.Font("Klee", 1, 24)); // NOI18N
        lblDoctorInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoctorInfo.setText("New Doctor Info");

        lblDOB.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblDOB.setText("Date of Birth:");

        lblPhoneNum.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblPhoneNum.setText("Phone Number:");

        lblEmailAdd.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblEmailAdd.setText("Email Address:");

        lblGender.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblGender.setText("Gender:");

        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "Male", "Female", "Non-Binary", "Prefer Not to Say", " " }));

        lblEmployeeID.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblEmployeeID.setText("Employee ID:");

        txtEmployeeID.setText("-1");

        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        txtDOB.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));
        txtDOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDOBActionPerformed(evt);
            }
        });

        lblHospital.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblHospital.setText("Hospital:");

        lblMajor.setFont(new java.awt.Font("Klee", 1, 14)); // NOI18N
        lblMajor.setText("Major:");

        javax.swing.GroupLayout DoctorCreateJPanelLayout = new javax.swing.GroupLayout(DoctorCreateJPanel);
        DoctorCreateJPanel.setLayout(DoctorCreateJPanelLayout);
        DoctorCreateJPanelLayout.setHorizontalGroup(
            DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblCreateAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblDoctorInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                        .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(lblMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                        .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                .addComponent(lblCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(lblCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCreate)
                                .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                    .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                            .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblGender))
                                            .addGap(18, 18, 18)
                                            .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(87, 87, 87)
                                    .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                                            .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtDOB))))))
                        .addContainerGap(136, Short.MAX_VALUE))))
        );
        DoctorCreateJPanelLayout.setVerticalGroup(
            DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorCreateJPanelLayout.createSequentialGroup()
                .addComponent(lblCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreatePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(lblDoctorInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmailAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGender)
                    .addComponent(cmbGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(DoctorCreateJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHospital, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMajor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnCreate)
                .addGap(70, 70, 70))
        );

        DoctorWorkAreaJPanel.setBackground(new java.awt.Color(51, 255, 51));

        javax.swing.GroupLayout DoctorWorkAreaJPanelLayout = new javax.swing.GroupLayout(DoctorWorkAreaJPanel);
        DoctorWorkAreaJPanel.setLayout(DoctorWorkAreaJPanelLayout);
        DoctorWorkAreaJPanelLayout.setHorizontalGroup(
            DoctorWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 811, Short.MAX_VALUE)
        );
        DoctorWorkAreaJPanelLayout.setVerticalGroup(
            DoctorWorkAreaJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 619, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(DoctorLoginJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DoctorCreateJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(DoctorWorkAreaJPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DoctorCreateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DoctorWorkAreaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DoctorLoginJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(DoctorCreateJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(DoctorWorkAreaJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pwdPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPasswordActionPerformed

    private void btnCreateAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateAccountActionPerformed
        // TODO add your handling code here:
        DoctorLoginJPanel.setVisible(false);
        DoctorCreateJPanel.setVisible(true);
        
    }//GEN-LAST:event_btnCreateAccountActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        if (txtEmployeeID.getText().contains("[a-zA-Z]+")){
            txtEmployeeID.setText("-1");
        }
        
//        Date nonedate = new Date();

//        if (!txtDOB.getValue().equals(nonedate)){
//            Date DOB = (Date)txtDOB.getValue();
//
//        }
        String Username = txtCreateUsername.getText();
        String Password = txtCreatePassword.getText();
        String Name = txtName.getText();
        Date DOB = (Date)txtDOB.getValue();
        int EmployeeID = Integer.parseInt(txtEmployeeID.getText());
        String Gender = cmbGender.getSelectedItem().toString();
        String PhoneNum = txtPhoneNum.getText();
        String EmailAdd = txtEmailAdd.getText();
        String Hospital = txtHospital.getText();
        String Major = txtMajor.getText();
        
        int nameflag = 0;
        char[] charArray = Name.toCharArray();
        for(char c:charArray)
        {
        if (!Character.isLetter(c))
            nameflag = 1;
        }
        
        int phoneflag = 0;
        char[] PhoneArray = PhoneNum.toCharArray();
        for(char c:PhoneArray)
        {
        if (!Character.isDigit(c))
            phoneflag = 1;
        }
        
        int saveflag = 1;
        if (Username.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Username.");
            saveflag = 0;
        }
        if (Password.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Password.");   
            saveflag = 0;
        }
        if (Name.equals("") || nameflag == 1){
            JOptionPane.showMessageDialog(this, "Invalid Name.");
            saveflag = 0;
        }
        if (EmployeeID < 0){
            JOptionPane.showMessageDialog(this, "Invalid EmployeeID.");
            saveflag = 0;
        }
        if (Gender.equals("None")){
            JOptionPane.showMessageDialog(this, "Invalid Gender.");
            saveflag = 0;
        }
        if (DOB == null){
            JOptionPane.showMessageDialog(this, "Invalid Date of Birth.");
            saveflag = 0;
        }
        if (PhoneNum.length() != 10 || phoneflag == 1){
            JOptionPane.showMessageDialog(this, "Invalid Phone Number.");
            saveflag = 0;
        }
        if (EmailAdd.equals("") || !EmailAdd.contains("@")){
            JOptionPane.showMessageDialog(this, "Invalid Email Address.");
            saveflag = 0;
        }
        if (Hospital.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Hospital.");
            saveflag = 0;
        }
        if (Major.equals("")){
            JOptionPane.showMessageDialog(this, "Invalid Major.");
            saveflag = 0;
        }
        
        else if (saveflag == 1){
        doctor ei = set.addNewDoctor();
        ei.setUsername(Username);
        ei.setPassword(Password);
        ei.setPhoneNum(PhoneNum);
        ei.setEmailAdd(EmailAdd);
        ei.setEmployeeID(EmployeeID);
        ei.setGender(Gender);
        ei.setName(Name);
        ei.setDOB((Date)txtDOB.getValue());
        JOptionPane.showMessageDialog(this, "Doctor Account Created.");
        
        txtCreateUsername.setText("");
        txtCreatePassword.setText("");
        txtName.setText("");
        txtDOB.setText("");
        txtEmployeeID.setText("");
        cmbGender.setSelectedIndex(0);
        txtPhoneNum.setText("");
        txtEmailAdd.setText("");
        txtEmployeeID.setText("-1");
        txtHospital.setText("");
        txtMajor.setText("");
        
        DoctorCreateJPanel.setVisible(false);
        DoctorLoginJPanel.setVisible(true);
        }
        
        
        
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void txtDOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDOBActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        String username = txtUsername.getText();
        String password = pwdPassword.getText();
        int flag = 0;
        for (doctor ei : set.getHistory()){
            if (ei.getUsername().equals(username) & (ei.getPassword().equals(password))){
                flag = 1;
                DoctorLoginJPanel.setVisible(false);
                DoctorWorkAreaJPanel.setVisible(true);
            }
        }
        if(flag == 0){
            JOptionPane.showMessageDialog(this, "Wrong Username or Password.");
        }
//        admin ei = set.getHistory();
//        if (ei.getUsername().equals(username) & ei.getPassword().equals(password)){
//        
//    }
        
//        for(admin admin: this.set){
//            if (admin.getUsername().equals(username) and admin.getPassword().equals(password)){
//            
//        }
//        }
//        txtUsername.getText();
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtCreateUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateUsernameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorCreateJPanel;
    private javax.swing.JPanel DoctorLoginJPanel;
    private javax.swing.JPanel DoctorWorkAreaJPanel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnCreateAccount;
    private javax.swing.JButton btnLogin;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel lblCreateAccount;
    private javax.swing.JLabel lblCreatePassword;
    private javax.swing.JLabel lblCreateUsername;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDoctorInfo;
    private javax.swing.JLabel lblDoctorLogin;
    private javax.swing.JLabel lblEmailAdd;
    private javax.swing.JLabel lblEmployeeID;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblHospital;
    private javax.swing.JLabel lblMajor;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNewUser;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhoneNum;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pwdPassword;
    private javax.swing.JPasswordField txtCreatePassword;
    private javax.swing.JTextField txtCreateUsername;
    private javax.swing.JFormattedTextField txtDOB;
    private javax.swing.JTextField txtEmailAdd;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtHospital;
    private javax.swing.JTextField txtMajor;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhoneNum;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
